import { defaultPackFormat, exportPack, packKindForPath } from "./pack-exporter.js";

const STORAGE = "datapack-schema-studio.v1";
const SCHEMA_INDEX_URL = "./schemas/index.txt?v=4";
const NAMESPACE_NAMES_URL = "./schemas/namespaces.json?v=1";
let namespaceNames = {};
const starterRegistry = {
  "minecraft:item": ["minecraft:air", "minecraft:diamond", "minecraft:diamond_sword", "minecraft:emerald", "minecraft:iron_ingot", "minecraft:stick", "minecraft:stone"],
  "minecraft:item_tag": ["minecraft:logs", "minecraft:planks", "minecraft:stone_crafting_materials"]
};
const dictionaries = {
  zh: { "app.subtitle":"JSON Schema 动态编辑器", language:"语言", workspace:"工作区", workspaceEmpty:"尚未编辑任何 JSON 文件", tools:"工具", configuration:"配置", savedInBrowser:"已保存到此浏览器", editorDescription:"由 Schema 驱动的文档编辑器，带本地注册表补全。", formHint:"由当前 Schema 生成的字段", jsonHint:"直接编辑 JSON 源码", exportJson:"导出 JSON", schemaVersion:"Schema 版本", schemas:"Schema", registryIndex:"注册表索引", registryHint:"对应 Identifier 字段可使用这些值。", schemaSource:"Schema 源码", form:"表单", json:"JSON", applyJson:"应用 JSON", registryEntry:"注册表条目", registryId:"注册表 ID", entryId:"条目 ID", cancel:"取消", save:"保存", add:"添加条目", remove:"移除", required:"必填", invalidSchema:"Schema 无效：", invalidJson:"JSON 无效：", updated:"已更新", noSchema:"请先选择一个 Schema", newDocument:"新建文档", documentName:"文档名称", title:"标题", value:"值", type:"类型", suggestions:"建议值，可自行输入", strictEnum:"请选择一个允许的值", objectKey:"属性名称", addProperty:"添加属性", duplicateKey:"属性名已存在", sourceChanged:"源码已更新", entrySaved:"注册表条目已保存" },
  en: { "app.subtitle":"Dynamic JSON Schema editor", language:"Language", workspace:"Workspace", workspaceEmpty:"No edited JSON files yet", tools:"Tools", configuration:"Configuration", savedInBrowser:"Saved in this browser", editorDescription:"Schema-driven document editor with local registry completion.", formHint:"Fields generated from the active schema", jsonHint:"Direct source editing", exportJson:"Export JSON", schemaVersion:"Schema version", schemas:"Schemas", registryIndex:"Registry index", registryHint:"Values are offered to matching identifier fields.", schemaSource:"Schema source", form:"Form", json:"JSON", applyJson:"Apply JSON", registryEntry:"Registry entry", registryId:"Registry ID", entryId:"Entry ID", cancel:"Cancel", save:"Save", add:"Add entry", remove:"Remove", required:"Required", invalidSchema:"Invalid schema: ", invalidJson:"Invalid JSON: ", updated:"Updated", noSchema:"Select a schema first", newDocument:"New document", documentName:"Document name", title:"Title", value:"Value", type:"Type", suggestions:"Suggested values; custom input allowed", strictEnum:"Choose an allowed value", objectKey:"Property name", addProperty:"Add property", duplicateKey:"Property name already exists", sourceChanged:"Source updated", entrySaved:"Registry entry saved" }
};
Object.assign(dictionaries.zh, { schemaPath:"Schema 路径", outputPath:"目标文件", namespace:"命名空间", contentPath:"内容路径" });
Object.assign(dictionaries.en, { schemaPath:"Schema path", outputPath:"Output path", namespace:"Namespace", contentPath:"Content path" });
Object.assign(dictionaries.zh, { invalidSchemaPath:"$path \u5fc5\u987b\u662f\u5305\u542b <namespace> \u548c <path> \u5404\u4e00\u6b21\u7684 data/... .json \u8def\u5f84" });
Object.assign(dictionaries.en, { invalidSchemaPath:"$path must be a data/... .json path containing <namespace> and <path> exactly once" });
Object.assign(dictionaries.zh, { exportPack:"\u5bfc\u51fa ZIP", packExportTitle:"\u5bfc\u51fa Minecraft \u5305", packName:"\u5305\u540d\u79f0", packDescription:"\u63cf\u8ff0", packFormat:"Pack format", createPack:"\u521b\u5efa ZIP", datapack:"\u6570\u636e\u5305", resourcepack:"\u8d44\u6e90\u5305", zipExported:"ZIP \u5df2\u5bfc\u51fa", invalidSchemaPath:"$path \u5fc5\u987b\u662f\u5305\u542b <namespace> \u548c <path> \u5404\u4e00\u6b21\u7684 data/... \u6216 assets/... .json \u8def\u5f84" });
Object.assign(dictionaries.en, { exportPack:"Export ZIP", packExportTitle:"Export Minecraft pack", packName:"Pack name", packDescription:"Description", packFormat:"Pack format", createPack:"Create ZIP", datapack:"Datapack", resourcepack:"Resource pack", zipExported:"ZIP exported", invalidSchemaPath:"$path must be a data/... or assets/... .json path containing <namespace> and <path> exactly once" });
Object.assign(dictionaries.zh, { home:"\u9996\u9875", homeEyebrow:"\u6570\u636e\u5305\u5185\u5bb9", homeTitle:"\u9009\u62e9\u8981\u7f16\u8f91\u7684\u5185\u5bb9", homeDescription:"\u4ece Schema \u7d22\u5f15\u4e2d\u9009\u62e9\u4e00\u79cd\u5185\u5bb9\u5f00\u59cb\u7f16\u3002", openEditor:"\u6253\u5f00\u7f16\u8f91\u5668", schemaDescription:"\u63cf\u8ff0", targetTemplate:"\u8f93\u51fa\u6a21\u677f", allFolders:"\u5168\u90e8", rootFolder:"\u6839\u76ee\u5f55" });
Object.assign(dictionaries.en, { home:"Home", homeEyebrow:"DATAPACK CONTENT", homeTitle:"Choose content to edit", homeDescription:"Select a schema from the index to start editing.", openEditor:"Open editor", schemaDescription:"Description", targetTemplate:"Output template", allFolders:"All", rootFolder:"Root" });
let state = loadState();
const $ = (selector) => document.querySelector(selector);
const el = (tag, attrs = {}, ...children) => { const node = document.createElement(tag); Object.entries(attrs).forEach(([key,value]) => { if (key === "class") node.className = value; else if (key === "text") node.textContent = value; else if (key.startsWith("on")) node.addEventListener(key.slice(2), value); else if (value !== undefined && value !== null) node.setAttribute(key,value); }); node.append(...children.flat().filter(Boolean)); return node; };
const t = (key) => dictionaries[state.locale][key] || dictionaries.zh[key] || key;

function schemaVersions(schema) { return Array.isArray(schema?.$version) ? schema.$version : (schema?.$version ? [schema.$version] : []); }
function schemaPrimaryVersion(schema) { return schemaVersions(schema)[0] || ""; }
function supportsVersion(schema, version) { return schemaVersions(schema).includes(version); }
function schemaKey(schema) { return `${schema.id}@${schemaVersions(schema).join(",") || "unversioned"}`; }
function schemaForKey(key, version=state.selectedVersion) { const id=String(key || "").split("@")[0]; return state.schemas.find((schema)=>schemaKey(schema)===key) || state.schemas.find((schema)=>schema.id===id && supportsVersion(schema,version)) || state.schemas.find((schema)=>schema.id===id); }
function localeKeys() { return state.locale === "zh" ? ["zh_cn", "zh-CN", "zh"] : ["en_us", "en-US", "en"]; }
function localized(schema, key) { const values=schema?.[`$${key}`]; if (values && typeof values === "object") for (const locale of localeKeys()) if (typeof values[locale] === "string" && values[locale]) return values[locale]; return schema?.[key] || ""; }
function namespaceLabel(value) { const [namespace,...rest]=String(value || "").split(":"); const names=namespaceNames[namespace]; const translated=names && localeKeys().map((locale)=>names[locale]).find(Boolean); return translated ? [translated,rest.join(":")].filter(Boolean).join(" · ") : value; }
function registryLabel(value) { const schema=state.schemas.find((item)=>item.$registry===value && supportsVersion(item,state.selectedVersion)) || state.schemas.find((item)=>item.$registry===value); return schema ? localized(schema,"title") || namespaceLabel(value) : namespaceLabel(value); }
function latestVersion(schemas) { return [...new Set(schemas.flatMap(schemaVersions))].sort((left,right)=>right.localeCompare(left))[0] || ""; }
function ensureHomeVersion() { if (state.activeView !== "home") return; const candidates=state.schemas.filter((schema)=>state.activeFolder === "all" || schema.$folder===state.activeFolder); if (candidates.length && !candidates.some((schema)=>supportsVersion(schema,state.selectedVersion))) state.selectedVersion=latestVersion(candidates); }
function startDocument(schema) { state.activeSchema=schemaKey(schema); if (!supportsVersion(schema,state.selectedVersion)) state.selectedVersion=schemaPrimaryVersion(schema); state.title=localized(schema,"title") || schema.id; state.documentPath="untitled"; state.data=defaultFor(schema); state.activeView="editor"; }
function loadState() { const defaults={ locale:"zh", theme:matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light", schemas:[], typeLibraries:[], activeView:"home", activeFolder:"all", selectedVersion:"26.1.2", versionPreferenceMigrated:true, registry:starterRegistry, activeSchema:"loot-table@1.21.1", namespace:"example", documentPath:"untitled", title:"Untitled loot table", sidebarWidth:260, sidebarCollapsed:false, documents:[], data:{} }; try { const stored=JSON.parse(localStorage.getItem(STORAGE) || "{}"); const { schemas:_schemas, typeLibraries:_typeLibraries, ...persisted }=stored; return {...defaults,...persisted,selectedVersion:stored.versionPreferenceMigrated ? (stored.selectedVersion || defaults.selectedVersion) : defaults.selectedVersion,versionPreferenceMigrated:true,schemas:[],typeLibraries:[],registry:stored.registry || starterRegistry,documents:Array.isArray(stored.documents) ? stored.documents : []}; } catch { return defaults; } }
function save() { const { schemas:_schemas, typeLibraries:_typeLibraries, ...persisted }=state; localStorage.setItem(STORAGE, JSON.stringify(persisted)); }
function activeSchema() { return schemaForKey(state.activeSchema) || state.schemas[0]; }
function resolvedOutputPath(schema=activeSchema()) { return (schema?.$path || "data/<namespace>/<path>.json").replaceAll("<namespace>",state.namespace || "example").replaceAll("<path>",state.documentPath || "untitled"); }
function validateOutputPath(path) { const occurrences=(token)=>path.split(token).length-1; if (typeof path !== "string" || !packKindForPath(path) || !path.endsWith(".json") || occurrences("<namespace>") !== 1 || occurrences("<path>") !== 1) throw new Error(t("invalidSchemaPath")); }
function validateSchema(schema) { if (!schema?.id || !schema.$version || typeof schema !== "object" || !schemaVersions(schema).length || !schemaVersions(schema).every((version)=>typeof version === "string" && version)) throw new Error("Schema must include id and a string or string-array $version"); if (schema.$library) { if (!schema.$types || typeof schema.$types !== "object") throw new Error("Type library must include a $types object"); return schema; } validateOutputPath(schema.$path); return schema; }
function folderForPath(path) { const segments=path.replaceAll("\\","/").split("/"); return segments.length > 1 ? segments.slice(0,-1).join("/") : ""; }
async function loadSchemaCatalog() { try { const indexResponse=await fetch(SCHEMA_INDEX_URL); if (!indexResponse.ok) throw new Error(`HTTP ${indexResponse.status}`); const indexUrl=new URL(SCHEMA_INDEX_URL,location.href); const paths=(await indexResponse.text()).split(/\r?\n/).map((path)=>path.trim()).filter((path)=>path && !path.startsWith("#")); const entries=await Promise.all(paths.map(async(path)=>{ const response=await fetch(new URL(path,indexUrl)); if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`); return { ...validateSchema(await response.json()), $catalogPath:path, $folder:folderForPath(path) }; })); const libraries=entries.filter((schema)=>schema.$library); const schemas=entries.filter((schema)=>!schema.$library); if (!schemas.length) throw new Error("The schema index contains no document schemas"); const catalogVersions=new Set(); for (const schema of entries) for (const version of schemaVersions(schema)) { const key=`${schema.id}@${version}`; if (catalogVersions.has(key)) throw new Error("Schema id and version combinations must be unique"); catalogVersions.add(key); } state.schemas=schemas; state.typeLibraries=libraries; if (!schemas.some((schema)=>schemaKey(schema)===state.activeSchema)) state.activeSchema=schemaKey(schemas[0]); if (!new Set(["all",...schemas.map((schema)=>schema.$folder)]).has(state.activeFolder)) state.activeFolder="all"; ensureHomeVersion(); state.data=defaultFor(activeSchema()); save(); renderAll(); } catch(error) { state.schemas=[]; state.typeLibraries=[]; renderAll(); setStatus(`Schema catalog unavailable: ${error.message}`,"error"); } }
async function loadNamespaceNames() { try { const response=await fetch(NAMESPACE_NAMES_URL); if (!response.ok) throw new Error(`HTTP ${response.status}`); const data=await response.json(); namespaceNames=data && typeof data === "object" ? data : {}; renderAll(); } catch { namespaceNames={}; } }
function renderOutputPath() { $("#output-path").textContent=resolvedOutputPath(); }
function setStatus(message, kind="ok") { const node=$("#validation-status"); node.textContent=message; node.className=`status ${kind}`; }
function openPackDialog() { const schema=activeSchema(); if (!schema) return setStatus(t("noSchema"),"error"); const path=resolvedOutputPath(schema); const kind=packKindForPath(path); if (!kind) return setStatus(t("invalidSchemaPath"),"error"); $("#pack-kind").textContent=t(kind === "data" ? "datapack" : "resourcepack"); $("#pack-path").textContent=path; $("#pack-name").value=state.packName || state.title || "minecraft-pack"; $("#pack-description").value=state.packDescription || state.title || "Minecraft pack"; $("#pack-format").value=defaultPackFormat(state.selectedVersion,kind); $("#pack-dialog").showModal(); }
function createPack() { const schema=activeSchema(); const path=resolvedOutputPath(schema); rememberDocument(); state.packName=$("#pack-name").value.trim(); state.packDescription=$("#pack-description").value.trim(); const kind=exportPack({path,data:state.data,name:state.packName,description:state.packDescription,version:state.selectedVersion,packFormat:Number($("#pack-format").value)}); save(); $("#pack-dialog").close(); renderSchemas(); setStatus(`${t("zipExported")}: ${t(kind === "data" ? "datapack" : "resourcepack")}`); }
function applyLocale() { document.documentElement.lang=state.locale === "zh" ? "zh-CN" : "en"; document.title="Datapack Schema Studio"; document.querySelectorAll("[data-i18n]").forEach((node)=>node.textContent=t(node.dataset.i18n)); document.querySelectorAll("[data-language]").forEach((button)=>{const selected=button.dataset.language===state.locale;button.classList.toggle("selected",selected);button.querySelector(".language-check").textContent=selected ? "✓" : "";}); }
function defaultFor(schema) { schema=resolve(schema); if (schema.default !== undefined) return structuredClone(schema.default); if (schema.type === "object") { const value={}; for (const key of schema.required || []) if (schema.properties?.[key]) value[key]=defaultFor(schema.properties[key]); return value; } if (schema.type === "array") return []; if (schema.type === "boolean") return false; if (schema.type === "number" || schema.type === "integer") return schema.minimum ?? 0; return schema.enum?.[0] ?? ""; }
function matchesType(schema, value) { schema=resolve(schema); if (schema.type === "object") return value && typeof value === "object" && !Array.isArray(value); if (schema.type === "array") return Array.isArray(value); return schema.type ? typeof value === schema.type : false; }
function referencedType(type) {
  const local=activeSchema()?.$types?.[type];
  if (local) return local;
  const separator=String(type || "").indexOf("#");
  if (separator < 1) return null;
  const libraryId=type.slice(0, separator), typeId=type.slice(separator + 1);
  const version=schemaPrimaryVersion(activeSchema());
  return state.typeLibraries.find((library)=>library.id === libraryId && supportsVersion(library, version))?.$types?.[typeId] || null;
}
function resolve(schema, value) {
  if (!schema) return {};
  const referenced=schema.$type ? referencedType(schema.$type) : null;
  const resolved=referenced ? { ...referenced, ...schema, $type:undefined } : schema;
  if (!Array.isArray(resolved.oneOf)) return resolved;
  const selected=resolved.oneOf.find((candidate)=>matchesType(candidate,value)) || resolved.oneOf[0];
  return resolve({ ...resolved, ...selected, oneOf:undefined },value);
}
function resolveVariant(schema, value) { const variant=schema?.$variants?.[value?.type]; if (!variant) return schema; return { ...schema, ...variant, properties:{ ...schema.properties, ...variant.properties }, required:[...new Set([...(schema.required || []),...(variant.required || [])])], additionalProperties:variant.additionalProperties ?? schema.additionalProperties }; }
function update(path, value) { if (!path.length) state.data=value; else { let target=state.data; path.slice(0,-1).forEach((piece)=>target=target[piece]); target[path.at(-1)]=value; } sync(); }
function remove(path) { if (!path.length) return; let target=state.data; path.slice(0,-1).forEach((piece)=>target=target[piece]); Array.isArray(target) ? target.splice(path.at(-1),1) : delete target[path.at(-1)]; sync(); }
function rememberDocument() { const schema=activeSchema(); if (!schema || state.activeView !== "editor") return; const path=resolvedOutputPath(schema); const document={path,schemaKey:schemaKey(schema),namespace:state.namespace,documentPath:state.documentPath,title:state.title,data:structuredClone(state.data),updatedAt:Date.now()}; state.documents=[...state.documents.filter((entry)=>entry.path!==path),document].sort((left,right)=>left.path.localeCompare(right.path)); }
function sync() { renderForm(); rememberDocument(); save(); $("#json-source").value=JSON.stringify(state.data,null,2); renderSchemas(); }

// A schema node's id selects its DOM builder, keeping field renderers independently extensible.
const builders = new Map();
function registerBuilder(id, builder) { builders.set(id,builder); }
function builderId(schema, value) { schema=resolve(schema,value); if (schema.$variantType) return "variant-type"; if (schema.enum) return schema.$suggstion ? "suggestion" : "enum"; if (schema.$registry && (schema.type === "string" || !schema.type)) return "registry"; return schema.type || "unknown"; }
function buildField(schema, value, path, label, required=false) { schema=resolve(schema,value); const body=(builders.get(builderId(schema,value)) || builders.get("unknown"))(schema,value,path); const name=localized(schema,"title") || label || t("value"); const meta=[localized(schema,"description"), required ? t("required") : ""].filter(Boolean).join(" · "); return el("section",{class:"field"}, el("div",{class:"field-top"},el("span",{class:"field-name",text:name}), required ? el("span",{class:"required",text:"*"}):null), meta ? el("div",{class:"field-description",text:meta}):null, el("div",{class:"field-control"},body)); }
function inputControl(type, value, onChange, attrs={}) { const input=el("input",{type, value:value ?? "", ...attrs}); input.addEventListener("change",()=>onChange(type === "number" || type === "range" ? Number(input.value) : input.value)); return input; }
registerBuilder("string", (schema,value,path) => inputControl("text",value,(next)=>update(path,next), schema.pattern ? {pattern:schema.pattern}:{}));
registerBuilder("number", (schema,value,path) => inputControl("number",value,(next)=>update(path,next), {min:schema.minimum,max:schema.maximum,step:schema.multipleOf || "any"}));
registerBuilder("integer", (schema,value,path) => inputControl("number",value,(next)=>update(path,Math.trunc(next)), {min:schema.minimum,max:schema.maximum,step:"1"}));
registerBuilder("boolean", (_schema,value,path) => { const input=el("input",{class:"boolean",type:"checkbox"}); input.checked=Boolean(value); input.addEventListener("change",()=>update(path,input.checked)); return el("label",{},input,document.createTextNode(input.checked ? "true" : "false")); });
registerBuilder("enum", (schema,value,path) => { const select=el("select"); schema.enum.forEach((option)=>select.append(el("option",{value:option,text:option}))); select.value=schema.enum.includes(value) ? value : schema.enum[0]; select.addEventListener("change",()=>update(path,select.value)); return el("div",{class:"enum-suggestion"},select,el("small",{text:t("strictEnum")})); });
registerBuilder("variant-type", (schema,value,path) => { const select=el("select"); schema.enum.forEach((option)=>select.append(el("option",{value:option,text:option}))); select.value=schema.enum.includes(value) ? value : schema.enum[0]; select.addEventListener("change",()=>update(path,select.value)); return el("div",{class:"enum-suggestion variant-type"},select,el("small",{text:t("type")})); });
registerBuilder("suggestion", (schema,value,path) => { const id=`choices-${path.join("-") || "root"}`; const input=inputControl("text",value,(next)=>update(path,next),{list:id}); return el("div",{class:"enum-suggestion"},input,el("datalist",{id},schema.enum.map((option)=>el("option",{value:option}))),el("small",{text:t("suggestions")})); });
registerBuilder("registry", (schema,value,path) => { const id=`registry-${path.join("-") || "root"}`; const values=state.registry[schema.$registry] || []; const input=inputControl("text",value,(next)=>update(path,next),{list:id,placeholder:schema.$registry}); return el("div",{class:"enum-suggestion"},input,el("datalist",{id},values.map((entry)=>el("option",{value:entry}))),el("small",{text:schema.$registry})); });
registerBuilder("array", (schema,value,path) => { const items=Array.isArray(value) ? value : []; const list=el("div",{class:"array-items"}); items.forEach((item,index)=>list.append(el("div",{class:"array-row"},buildField(schema.items,item,[...path,index],`${labelFor(schema.items)} ${index+1}`),el("button",{type:"button",title:t("remove"),text:"×",onclick:()=>remove([...path,index])})))); const add=el("button",{class:"add-button",type:"button",text:`+ ${t("add")}`,onclick:()=>{ if (!Array.isArray(value)) update(path,[]); else { value.push(defaultFor(schema.items)); sync(); } }}); return el("div",{},list,add); });
registerBuilder("object", (schema,value,path) => { const object=value && typeof value === "object" && !Array.isArray(value) ? value : {}; schema=resolveVariant(schema,object); const box=el("div",{class:"object"}); const withRemove=(field,key)=>el("div",{class:"object-field"},field,el("button",{class:"object-remove",type:"button",title:t("remove"),text:"×",onclick:()=>remove([...path,key])})); Object.entries(schema.properties || {}).forEach(([key,child])=> { const present=object[key] !== undefined; const needed=(schema.required || []).includes(key); const fieldSchema=key === "type" && schema.$variants ? { ...child, $variantType:true } : child; if (present || needed) { if (!present) object[key]=defaultFor(fieldSchema); const field=buildField(fieldSchema,object[key],[...path,key],key,needed); box.append(needed ? field : withRemove(field,key)); } else { const add=el("button",{class:"add-button",type:"button",text:`+ ${localized(resolve(fieldSchema),"title") || key}`,onclick:()=>{object[key]=defaultFor(fieldSchema);sync();}}); box.append(add); } }); if (schema.additionalProperties) { Object.keys(object).filter((key)=>!schema.properties?.[key]).forEach((key)=>box.append(withRemove(buildField(schema.additionalProperties,object[key],[...path,key],key,false),key))); const keyInput=el("input",{placeholder:t("objectKey")}); const add=el("button",{class:"add-button",type:"button",text:`+ ${t("addProperty")}`,onclick:()=>{ const key=keyInput.value.trim(); if (!key || Object.hasOwn(object,key)) return setStatus(t("duplicateKey"),"error"); object[key]=defaultFor(schema.additionalProperties);sync(); }}); box.append(el("div",{class:"type-picker"},keyInput,add)); } return box; });
registerBuilder("unknown", (_schema,value,path) => { const area=el("textarea",{text:JSON.stringify(value ?? null,null,2)}); area.addEventListener("change",()=>{try{update(path,JSON.parse(area.value));}catch(error){setStatus(`${t("invalidJson")}${error.message}`,"error");}}); return area; });
function labelFor(schema) { return localized(resolve(schema),"title") || t("value"); }
function renderForm() { const schema=activeSchema(); const root=$("#editor-form"); root.replaceChildren(); if (!schema) { root.textContent=t("noSchema"); return; } $("#schema-registry").textContent=[registryLabel(schema.$registry || "No registry"),state.selectedVersion ? `v${state.selectedVersion}` : ""].filter(Boolean).join(" / "); $("#document-title").textContent=state.title; if (schema.$type && schema.$types?.[schema.$type]) root.append(buildTypePicker(schema,state.data,[])); root.append(buildField(schema,state.data,[],localized(schema,"title") || t("documentName"),true)); }
function buildTypePicker(schema,value,path) { const typeNames=Object.keys(schema.$types || {}); const picker=el("select"); typeNames.forEach((key)=>picker.append(el("option",{value:key,text:localized(schema.$types[key],"title") || key}))); picker.value=schema.$type; picker.addEventListener("change",()=>{ schema.$type=picker.value; update(path,defaultFor(schema.$types[picker.value])); }); return el("div",{class:"type-picker"},el("span",{text:t("type")}),picker); }
function renderHome() { const home=$("#home-view"), editor=$("#editor-view"); const isHome=state.activeView === "home"; home.hidden=!isHome; editor.hidden=isHome; $("#home-nav").classList.toggle("active",isHome); if (!isHome) return; const folders=["all",...new Set(state.schemas.map((schema)=>schema.$folder).sort())]; const filter=$("#folder-filter"); filter.replaceChildren(...folders.map((folder)=>el("button",{class:`folder-button ${state.activeFolder===folder?"active":""}`,type:"button",text:folder === "all" ? t("allFolders") : (folder ? namespaceLabel(folder) : t("rootFolder")),onclick:()=>{state.activeFolder=folder;const candidates=state.schemas.filter((schema)=>folder === "all" || schema.$folder===folder);if (!candidates.some((schema)=>supportsVersion(schema,state.selectedVersion))) state.selectedVersion=latestVersion(candidates);save();renderAll();}}))); const visible=state.schemas.filter((schema)=>(state.activeFolder === "all" || schema.$folder===state.activeFolder) && supportsVersion(schema,state.selectedVersion)); const grid=$("#home-grid"); grid.replaceChildren(...visible.map((schema)=>{ const path=schema.$path || "data/<namespace>/<path>.json"; return el("article",{class:"schema-card"},el("div",{class:"schema-card-head"},el("span",{class:"schema-card-kind",text:registryLabel(schema.$registry || schema.id)}),el("span",{class:"schema-card-version",text:`v${state.selectedVersion || "?"}`})),el("h2",{text:localized(schema,"title") || schema.id}),el("p",{class:"schema-card-description",text:localized(schema,"description") || t("schemaDescription")}),el("div",{class:"schema-card-path"},el("span",{text:t("targetTemplate")}),el("code",{text:path})),el("button",{class:"button primary",type:"button",text:t("openEditor"),onclick:()=>{startDocument(schema);save();renderAll();}})); })); }
function openSchema(schema) { startDocument(schema); save(); renderAll(); }
function renderTree(entries, current) { return entries.map((entry)=>entry.document ? el("button",{class:`tree-file ${entry.document.path===resolvedOutputPath() && state.activeView!=="home"?"active":""}`,type:"button",title:entry.document.path,ondblclick:()=>{const schema=schemaForKey(entry.document.schemaKey);if(!schema)return;state.activeSchema=schemaKey(schema);state.namespace=entry.document.namespace;state.documentPath=entry.document.documentPath;state.title=entry.document.title;state.data=structuredClone(entry.document.data);state.activeView="editor";save();renderAll();}},el("span",{class:"tree-file-icon",text:"{}"}),el("span",{class:"tree-file-label",text:entry.name}),el("small",{text:"json"})) : el("div",{class:"tree-folder"},el("div",{class:"tree-folder-name",text:entry.name}),el("div",{class:"tree-folder-children"},renderTree(entry.children,current)))); }
function renderSchemas() { const current=activeSchema(); const root=[{name:"data",children:[]},{name:"assets",children:[]}], folders=new Map(root.map((entry)=>[entry.name,entry])); state.documents.forEach((document)=>{const parts=document.path.split("/");const name=parts.pop();let branch=root,key="";parts.forEach((part,index)=>{key=index ? `${key}/${part}` : part;if(!folders.has(key)){const folder={name:part,children:[]};folders.set(key,folder);branch.push(folder);}branch=folders.get(key).children;});branch.push({name,document});}); $("#schema-list").replaceChildren(...renderTree(root,current)); const versionSelect=$("#schema-version"); const versions=[...new Set(state.schemas.flatMap(schemaVersions))].sort((left,right)=>right.localeCompare(left)); versionSelect.replaceChildren(...versions.map((version)=>el("option",{value:version,text:version}))); if (versions.includes(state.selectedVersion)) versionSelect.value=state.selectedVersion; else { state.selectedVersion=versions[0] || ""; versionSelect.value=state.selectedVersion; } versionSelect.disabled=versions.length<2; }
function renderAll() { applyLocale(); renderHome(); renderSchemas(); const schema=activeSchema(); $("#json-source").value=JSON.stringify(state.data,null,2); $("#namespace-input").value=state.namespace; $("#content-path-input").value=state.documentPath; $("#header-registry").textContent=state.activeView === "home" ? t("home") : registryLabel(schema?.$registry || "No registry"); renderOutputPath(); renderForm(); }
function closeLanguageMenu() { $("#language-dropdown").hidden=true; $("#language-menu-toggle").setAttribute("aria-expanded","false"); }
$("#language-menu-toggle").addEventListener("click",(event)=>{event.stopPropagation();const dropdown=$("#language-dropdown");dropdown.hidden=!dropdown.hidden;$("#language-menu-toggle").setAttribute("aria-expanded",String(!dropdown.hidden));});
$("#language-dropdown").addEventListener("click",(event)=>event.stopPropagation());
document.querySelectorAll("[data-language]").forEach((button)=>button.addEventListener("click",()=>{state.locale=button.dataset.language;save();closeLanguageMenu();renderAll();}));
document.addEventListener("click",closeLanguageMenu);
$("#theme-toggle").addEventListener("click",()=>{state.theme=state.theme === "dark" ? "light":"dark";document.documentElement.dataset.theme=state.theme;save();});
$("#home-nav").addEventListener("click",()=>{state.activeView="home";save();renderAll();});
function applySidebar() { document.documentElement.style.setProperty("--sidebar-width",`${Math.min(460,Math.max(190,state.sidebarWidth || 260))}px`); document.documentElement.classList.toggle("sidebar-collapsed",Boolean(state.sidebarCollapsed)); $("#sidebar-collapse").textContent=state.sidebarCollapsed ? "›" : "‹"; $("#sidebar-collapse").setAttribute("aria-label",state.sidebarCollapsed ? "Expand sidebar" : "Collapse sidebar"); }
$("#sidebar-collapse").addEventListener("click",()=>{state.sidebarCollapsed=!state.sidebarCollapsed;save();applySidebar();});
let resizingSidebar=false;
$("#sidebar-resizer").addEventListener("pointerdown",(event)=>{if (state.sidebarCollapsed) return;resizingSidebar=true;event.currentTarget.setPointerCapture(event.pointerId);document.body.classList.add("resizing-sidebar");});
window.addEventListener("pointermove",(event)=>{if (!resizingSidebar) return;state.sidebarWidth=Math.min(460,Math.max(190,event.clientX));applySidebar();});
window.addEventListener("pointerup",()=>{if (!resizingSidebar) return;resizingSidebar=false;document.body.classList.remove("resizing-sidebar");save();});
$("#new-document").addEventListener("click",()=>{state.activeView="editor";state.title=prompt(t("documentName"),state.title)||state.title;state.data=defaultFor(activeSchema());sync();});
$("#export-pack").addEventListener("click",openPackDialog);
$("#pack-form").addEventListener("submit",(event)=>{if (event.submitter?.id!=="create-pack") return; event.preventDefault();try { createPack(); } catch(error) { setStatus(error.message,"error"); }});
$("#apply-json").addEventListener("click",()=>{try {state.data=JSON.parse($("#json-source").value);sync();setStatus(t("updated"));} catch(error) {setStatus(`${t("invalidJson")}${error.message}`,"error");}});
document.querySelectorAll(".tab").forEach((tab)=>tab.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach((node)=>node.classList.toggle("active",node===tab));$("#editor-form").hidden=tab.dataset.tab!=="form";$("#editor-json").hidden=tab.dataset.tab!=="json";}));
$("#schema-version").addEventListener("change",(event)=>{ state.selectedVersion=event.target.value; const current=activeSchema(); const compatible=state.schemas.find((schema)=>schema.id===current?.id && supportsVersion(schema,state.selectedVersion)); if (compatible && schemaKey(compatible)!==schemaKey(current)) { state.activeSchema=schemaKey(compatible);state.data=defaultFor(compatible);state.activeView="editor"; } save(); renderAll(); });
$("#namespace-input").addEventListener("input",(event)=>{ state.namespace=event.target.value.trim() || "example";rememberDocument();save();renderOutputPath();renderSchemas(); });
$("#content-path-input").addEventListener("input",(event)=>{ state.documentPath=event.target.value.trim().replace(/\.json$/i,"") || "untitled";rememberDocument();save();renderOutputPath();renderSchemas(); });
$("#import-document").addEventListener("click",()=>$("#file-input").click());$("#file-input").addEventListener("change",async(event)=>{const file=event.target.files[0];if(!file)return;try{state.data=JSON.parse(await file.text());state.title=file.name.replace(/\.json$/i,"");sync();}catch(error){setStatus(`${t("invalidJson")}${error.message}`,"error");}});
$("#export-document").addEventListener("click",()=>{const blob=new Blob([JSON.stringify(state.data,null,2)+"\n"],{type:"application/json"});const link=el("a",{href:URL.createObjectURL(blob),download:`${state.title||"datapack"}.json`});link.click();setTimeout(()=>URL.revokeObjectURL(link.href),500);});
document.documentElement.dataset.theme=state.theme; applySidebar(); renderAll(); loadSchemaCatalog(); loadNamespaceNames();
